#!/bin/sh

TODO_LOCATION="$HOME/Documents/notes/todo"
NOTES_LOCATION="$HOME/Documents/notes"

open_editor(){
    # Using nvim with tmux
    # wmctrl -a TMUX # Activate the window when opening notes/todos assuming the title is "TMUX"
    # tmux new-window 
    # tmux send-keys "$EDITOR $2 $1" Enter

    # Using Emacs with emacsclient
    # In your shell
    # export EDITOR="emacsclient -a '' --socket-name=MAIN"

    $EDITOR $2 $1 &
}

get_todo(){
    TD=$(grep -e '- TODO' "$TODO_LOCATION")
    NX=$(grep -e '- NEXT' "$TODO_LOCATION")
    DN=$(grep -e '- DONE' "$TODO_LOCATION")
    RES=$(echo "$TD\n\n$NX\n\n$DN")
    echo "$RES"
}

get_next(){
    TD=$(grep -e '- TODO' "$TODO_LOCATION")
    NX=$(grep -e '- NEXT' "$TODO_LOCATION")
    DN=$(grep -e '- DONE' "$TODO_LOCATION")
    RES=$(echo "$NX\n\n$TD\n\n$DN")
    echo "$RES"
}

get_done(){
    TD=$(grep -e '- TODO' "$TODO_LOCATION")
    NX=$(grep -e '- NEXT' "$TODO_LOCATION")
    DN=$(grep -e '- DONE' "$TODO_LOCATION")
    RES=$(echo "$DN\n\n$NX\n\n$TD")
    echo "$RES"
}

get_notes(){
    NOTES=$(ls -D "$NOTES_LOCATION")
    echo "$NOTES"
}
get_line_number(){
    LN=$(cat -n "$TODO_LOCATION" | grep -e "$1" | cut -f1)
    echo "$LN"
}

get_full(){
    FULL=$(sed -n "/${1}/,/^$/p" "$TODO_LOCATION")
    echo "$FULL"
}

get_full_cut(){
    cutted=$( echo "$1" | cut -f2)
    FULL=$(sed -n "/${cutted}/,/^$/p" "$TODO_LOCATION")
    echo "$FULL"
}

promote_item(){
    # Takes selected items keyword to search and keyword to replace
    echo "$1" | cut -f2 |
    while IFS= read -r item; do
      LINE=$(cat -n "$TODO_LOCATION" | grep -e "$item" | cut -f1 | tr -d ' ')
      sed -i "${LINE}s/${2}/${3}/" "$TODO_LOCATION"
    done
}

case $1 in
    d) mode="done";;
    n) mode="next";;
    o) mode="notes";;
    t) mode="todo";;
    *) mode="todo";;
esac

while true; do
    case "$mode" in
        done) mode_list="get_done";;
        next) mode_list="get_next";;
        todo) mode_list="get_todo";;
        notes) mode_list="get_notes";;
    esac

    dmenu_choice=$("$mode_list" | dmenu-suite -i -p "$mode" -c  -l 30 -ex 'ctrl-f,ctrl-g,ctrl-x,ctrl-l,ctrl-i,ctrl-o,ctrl-t,ctrl-n,ctrl-d,shift-enter')

    [ -z "$dmenu_choice" ] && exit 0

    case "$dmenu_choice" in
        ctrl-d*) mode="done";;
        ctrl-n*) mode="next";;
        ctrl-t*) mode="todo";;
        ctrl-f*) mode="notes";;
        ctrl-g*)
            grep=$(dmenu-suite -i -l 30 -p 'Grep Notes' -dy 'dmenu-todo-notes-ripgrep') || break
            file_line=$(echo "$grep" | cut -d ':' -f2)
            file_name=$(echo "$grep" | cut -d '/' -f1 | cut -d ':' -f1)
            "open_editor" "$NOTES_LOCATION/$file_name" "+$file_line" && break ;;
        ctrl-i*)
            note="$(echo | dmenu-suite -i -p 'New Note >')" || exit 0
            "open_editor" "$NOTES_LOCATION/$note.md" || exit 0; break ;;
        ctrl-l*)
            case "$mode" in
              todo|next|done) "get_full_cut" "$dmenu_choice" | dmenu-suite -c -p 'preview' -l 30 ;;
              notes) note_name=$(echo "$dmenu_choice" | cut -f2)
                  cat "$NOTES_LOCATION/$note_name" | dmenu-suite -p 'preview' -l 30;;
            esac ;;
        ctrl-x*)
            case "$mode" in
                todo) "promote_item" "$dmenu_choice" "TODO" "NEXT";;
                next) "promote_item" "$dmenu_choice" "NEXT" "DONE";;
            esac ;;
   shift-enter*) todo=$( echo "$dmenu_choice" | cut -f2 )
                echo ";- TODO $todo"| tr ';' '\n' >> "$TODO_LOCATION"; break;;
              *) case "$mode" in
                  todo|next|done)
                      LN=$(cat -n "$TODO_LOCATION" | grep -e "$dmenu_choice" | cut -f1 | tr -d ' ')
                      "open_editor" "$TODO_LOCATION" "+$LN"; break ;;
                  notes) "open_editor" "$NOTES_LOCATION/$dmenu_choice"; break ;;
                esac
    esac
done
