#!/bin/sh

# To use `wmctrl` to focus the Tmux window automatically on switch, you need to set its title in your .tmux.conf, and in this script.
# In .tmux.conf
# set-option -g set-titles-string 'TMUX' 

TMUX_TITLE="TMUX"

get_panes(){
    list=$(tmux list-panes -a -F '#S #T\t#D')

    #Filter out current pane
    # current_pane=$(tmux list-panes -F '#{pane_active} #D' | grep "^1" | cut -d ' ' -f2)
    # echo "$list" | grep -v "$current_pane" 

    echo "$list"
}
get_windows(){
    list=$(tmux list-windows -a -F '#{window_activity} #S #T\t#D' | sort -nr | cut -d ' '  -f2-)

    #Filter out current window
    # current_window=$(tmux list-windows -F '#{window_active} #D' | grep "^1" | cut -d ' ' -f2)
    # echo "$list" | grep -v "$current_window" 

    echo "$list"
}
get_sessions(){
    list=$(tmux list-sessions -F '#{session_activity} #S #T\t#D'| sort -nr | cut -d ' ' -f2-)

    #Filter out current session
    # current_session=$(tmux list-session | grep "attached" | cut -d ':' -f1)
    # echo "$list" | grep -v "$current_session" 

    echo "$list"
}

get_id(){
    echo "$1" | rev | cut -f1 | rev
}

case $1 in
    p) mode="panes";;
    w) mode="windows";;
    s) mode="sessions";;
    *) mode="panes";;
esac

while true; do
    case "$mode" in 
        panes) mode_list="get_panes";;
        windows) mode_list="get_windows";;
        sessions) mode_list="get_sessions";;
    esac

    dmenu_choice=$("$mode_list" | dmenu-suite -p "$mode" -c -l 30 -ex 'ctrl-p,ctrl-w,ctrl-s,ctrl-g,ctrl-x,ctrl-d')

    [ -z "$dmenu_choice" ] && exit 0

    case "$dmenu_choice" in
        ctrl-p*)mode="panes";;
        ctrl-w*)mode="windows";;
        ctrl-s*)mode="sessions";;
        ctrl-g*) case "$mode" in
                    panes) "get_id" "$dmenu_choice"  | xargs -I %% tmux join-pane -b -h -t:. -s %% ;; 
                    windows) "get_id" "$dmenu_choice" | xargs -I %% tmux move-window -s %% ;;
                esac; break ;;
        ctrl-x*) case "$mode" in
                    panes) "get_id" "$dmenu_choice"  | xargs -I %% tmux swap-pane -t %% -s:. ;; 
                    windows) "get_id" "$dmenu_choice" |xargs -I %% tmux swap-window -t %% -s:. ;; 
                esac; break ;;
        ctrl-d*) case "$mode" in
                    panes) "get_id" "$dmenu_choice" | xargs -I %% tmux kill-pane -t %% ;;
                    windows) "get_id" "$dmenu_choice" | xargs -I %% tmux kill-window -t %% ;;
                    sessions) "get_id" "$dmenu_choice" | xargs -I %% tmux kill-session -t %% ;;
                esac; break ;;
            *) case "$mode" in 
                    panes) "get_id" "$dmenu_choice" | xargs -I %% tmux switch-client -t %%  && wmctrl -a -F "$TMUX_TITLE";;
                    windows) "get_id" "$dmenu_choice" | xargs -I %% tmux switch-client -t %% && wmctrl -a -F "$TMUX_TITLE";;
                    sessions) "get_id" "$dmenu_choice" | xargs -I %% tmux switch-client -t %% && wmctrl -a -F "$TMUX_TITLE";;
               esac; break ;;
    esac 
done
